# Generated by Django 2.1.4 on 2019-03-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetBrands', '0002_assetbrand_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetbrand',
            name='description',
            field=models.TextField(default='This is a description.', max_length=300),
            preserve_default=False,
        ),
    ]
