# Generated by Django 2.1.4 on 2019-03-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetBrands', '0004_assetbrand_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetbrand',
            options={'verbose_name': 'Asset Brand', 'verbose_name_plural': 'Asset Brands'},
        ),
    ]
