# Generated by Django 2.1.4 on 2019-04-01 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0006_auto_20190325_0336'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.Branch'),
        ),
    ]
