# Generated by Django 2.1.4 on 2019-04-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permissions_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='branch',
            field=models.ForeignKey(on_delete=models.SET_NULL, to='branch.Branch'),
        ),
    ]
