# Generated by Django 2.1.4 on 2019-04-01 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190401_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.Branch'),
        ),
    ]
