# Generated by Django 2.1.4 on 2019-02-20 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default='1')),
                ('description', models.TextField(max_length=300)),
                ('status', models.CharField(choices=[('1', 'In Use'), ('2', 'In Storage'), ('3', 'In Maintenance'), ('4', 'Defective')], max_length=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_acquired', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_of_warranty', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_no', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100)),
                ('acquisition_cost', models.FloatField()),
                ('projected_life', models.DurationField()),
                ('accrued', models.FloatField()),
                ('balance', models.FloatField()),
                ('salvage_value', models.FloatField()),
                ('book_value', models.FloatField()),
            ],
        ),
    ]
