# Generated by Django 2.1.4 on 2019-02-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='accrued',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='book_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='salvage_value',
            field=models.FloatField(null=True),
        ),
    ]
