# Generated by Django 2.1.4 on 2019-02-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetBrands', '0001_initial'),
        ('assets', '0002_auto_20190220_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='brand',
            field=models.ForeignKey(default='1', on_delete=models.SET('None'), to='assetBrands.assetBrand'),
        ),
    ]
