# Generated by Django 2.1.4 on 2019-02-20 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assets_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assetBrands.assetBrand'),
        ),
    ]
