# Generated by Django 2.1.4 on 2019-02-21 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_auto_20190221_1829'),
        ('assets', '0005_assets_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.Branch'),
        ),
    ]
