# Generated by Django 2.1.4 on 2019-02-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assets_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='status',
            field=models.CharField(choices=[('In Use', None), ('In Storage', None), ('In Maintenance', None), ('Defective', None)], max_length=1),
        ),
    ]
