# Generated by Django 2.1.4 on 2019-02-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20190223_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='status',
            field=models.CharField(choices=[('In Use', 'In Use'), ('In Storage', 'In Storage'), ('In Maintenance', 'In Maintenance'), ('Defective', 'Defective')], max_length=1),
        ),
    ]
