# Generated by Django 2.1.4 on 2019-03-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20190301_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='counter',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='assets',
            name='dep_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='assets',
            name='display',
            field=models.CharField(default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='assets',
            name='acquisition_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
