# Generated by Django 2.1.4 on 2019-03-06 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_auto_20190307_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='date_acquired',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assets',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='end_of_warranty',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
