# Generated by Django 2.1.4 on 2019-08-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_auto_20190512_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='specifications',
            field=models.TextField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='assets',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
