# Generated by Django 2.1.4 on 2019-03-15 03:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_auto_20190814_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='it_dep_value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
    ]
