# Generated by Django 2.1.4 on 2019-03-24 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_auto_20190320_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='acquisition_cost',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='assets',
            name='project_life',
            field=models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='assets',
            name='salvage_value',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
