# Generated by Django 2.1.4 on 2019-03-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_auto_20190324_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assets',
            options={'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
    ]
