# Generated by Django 2.1.4 on 2019-04-01 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20190325_0336'),
        ('assets', '0027_auto_20190325_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.Vendors'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.Branch'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assetBrands.assetBrand'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assetCategories.assetCategory'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
