# Generated by Django 2.1.4 on 2019-04-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_auto_20190402_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='serial_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
