# Generated by Django 2.1.4 on 2019-04-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0029_auto_20190402_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='quantity',
        ),
    ]
