# Generated by Django 2.1.4 on 2019-03-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetCategories', '0003_assetcategory_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'verbose_name': 'Asset Category', 'verbose_name_plural': 'Asset Categories'},
        ),
    ]
