# Generated by Django 2.1.4 on 2019-02-28 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0010_auto_20190301_0031'),
        ('branch', '0002_auto_20190221_1829'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('ttype', models.CharField(choices=[('1', 'Maintenance'), ('2', 'Transfer'), ('3', 'Recover')], max_length=3)),
                ('status', models.CharField(choices=[('1', 'Queued'), ('2', 'Finished'), ('3', 'Past Due')], max_length=3)),
                ('description', models.TextField(max_length=300)),
                ('schedule', models.DateTimeField(default=django.utils.timezone.now)),
                ('assets_transact', models.ManyToManyField(to='assets.Assets')),
                ('branch_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='branch.Branch')),
                ('branch_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='branch.Branch')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.Vendors')),
            ],
        ),
    ]
