# Generated by Django 2.1.4 on 2019-03-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20190301_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='description',
            field=models.TextField(default='None', max_length=300),
        ),
    ]
