# Generated by Django 2.1.4 on 2019-03-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20190315_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
