# Generated by Django 2.1.4 on 2019-03-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20190316_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='ttype',
            field=models.CharField(choices=[('1', 'Maintenance'), ('2', 'Transfer'), ('3', 'Dispose'), ('4', 'Recover')], max_length=3),
        ),
    ]
