# Generated by Django 2.1.4 on 2019-03-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_assets_it_dep_value'),
        ('transactions', '0009_auto_20190316_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='archived_assets',
            field=models.ManyToManyField(limit_choices_to={'display': 0}, related_name='archived_assets', to='assets.Assets'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='assets_transact',
            field=models.ManyToManyField(limit_choices_to={'display': 1}, related_name='assets_transactions', to='assets.Assets'),
        ),
    ]
