# Generated by Django 2.1.4 on 2019-03-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20190320_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='close_date',
            field=models.DateField(null=True),
        ),
    ]
