# Generated by Django 2.1.4 on 2019-03-07 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_company_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owners',
        ),
        migrations.AddField(
            model_name='company',
            name='owners',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
