# Generated by Django 2.1.4 on 2019-03-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20190308_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='display',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
