# Generated by Django 2.1.4 on 2019-03-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20190318_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
