# Generated by Django 2.1.4 on 2019-02-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('contact_number', models.CharField(default='None', max_length=100)),
                ('contact_email', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
