# Generated by Django 2.1.4 on 2019-03-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendors_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='display',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
