# Generated by Django 2.1.4 on 2019-03-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendors_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendors',
            options={'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
    ]
