# Generated by Django 2.1.4 on 2019-04-01 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetCategories', '0004_auto_20190325_0336'),
        ('vendors', '0005_auto_20190325_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetCategories.assetCategory'),
            preserve_default=False,
        ),
    ]
