# Generated by Django 2.1.4 on 2019-03-07 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_auto_20190221_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
