# Generated by Django 2.1.4 on 2019-03-10 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_branch_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='display',
            field=models.CharField(default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
