# Generated by Django 2.1.4 on 2019-03-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_auto_20190318_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
    ]
